name: ci.yml
on: [pull_request, push, workflow_dispatch]

jobs:
  Terrascan:
    name: Terrascan Scan
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terrascan
        run: |
          curl -L "https://github.com/tenable/terrascan/releases/download/v1.18.11/terrascan_1.18.11_Linux_x86_64.tar.gz" > terrascan.tar.gz &&
          tar -xf terrascan.tar.gz terrascan &&
          sudo mv terrascan /usr/local/bin/ &&
          rm terrascan.tar.gz

      - name: Run TerraScan
        run: |
           # Load values from values.yaml
           terraformPath=$(cat values.yaml | grep 'terraformPath:' | awk '{print $2}')

           # Navigate to the directory containing Terraform code
           cd $config

           # Run TerraScan
           terrascan scan
        
