name: Terrascan Scan

on:
  push:
    branches:
      - '**'

jobs:
  terrascan-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Terrascan
      run: |
        curl -LJO https://github.com/accurics/terrascan/releases/latest/download/terrascan-bundle-linux-amd64.tar.gz
        tar -zxvf terrascan-bundle-linux-amd64.tar.gz
        sudo mv terrascan /usr/local/bin/terrascan
        terrascan version

    - name: Run Terrascan
      run: terrascan scan -d config
