name: TerraScan Workflow

on:
  push:
    branches:
      "**"

jobs:
  terrascan-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install TerraScan
      run: |
        # Download and install TerraScan
        curl -LJO https://github.com/accurics/terrascan/releases/latest/download/terrascan_${RUNNER_OS}_${RUNNER_ARCH}.tar.gz
        tar -xf terrascan_${RUNNER_OS}_${RUNNER_ARCH}.tar.gz
        sudo mv terrascan /usr/local/bin/
        rm terrascan_${RUNNER_OS}_${RUNNER_ARCH}.tar.gz

    - name: Run TerraScan
      run: |
        # Navigate to the directory containing Terraform code
        cd path/to/terraform/code

        # Run TerraScan
        terrascan scan
