name: OWASP ZAP Scan

on:
  push:
    branches:
      - zapscan

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install ZAP Proxy
        run: |
          sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

      - name: Run ZAP Spider
        run: zap-cli --quick-url http://localhost.com --spider -r -m 5

      - name: Run ZAP Active Scan
        run: zap-cli --quick-url http://localhost.com -r -m 5 -s active-scan
