name: Gitleaks Scan

on:
  push:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.4.1/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
      - name: Run gitleaks scan
        run: |
          gitleaks --verbose
      - name: Upload gitleaks report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-report
          path: gitleaks-report.txt
